/* ************************************************************************** */
/* SECTION: Create target SIF data structure                                  */
/* ************************************************************************** */

-- Each instance of "VARCHAR (111)" that is a placeholder datatype only.
-- Such placeholder datatypes will need to be replaced during mapping.

-- SUBSECTION: Tables with 0 in name implement SIF codes (no other dependencies)

  -- TO-DO

-- SUBSECTION: Tables with 1 in name define a new PK used by child 2 table(s) 

CREATE TABLE cdm_demo_gold.Dim1StaffPersonal (
     [RefId] CHAR (36) NOT NULL
    ,[LocalId] INT NOT NULL
    ,[StateProvinceId] VARCHAR (111) NULL
    ,[Title] VARCHAR (111) NULL
    ,[EmploymentStatus] VARCHAR (111) NULL
    ,CONSTRAINT [RefUnique_StaffPersonal] UNIQUE ([RefId])
    ,CONSTRAINT [RefUUID_StaffPersonal] CHECK ([RefId] LIKE '________-____-7___-____-____________')
    ,CONSTRAINT [PK_StaffPersonal] PRIMARY KEY ([LocalId])
);



-- SUBSECTION: Tables with 2 in name have FK referencing parent 1 table(s)

CREATE TABLE cdm_demo_gold.Dim2StaffList (
     [StaffRefId] CHAR (36)  NOT NULL
    ,[StaffLocalId] INT NOT NULL
    ,CONSTRAINT [FKRef_StaffList_StaffPersonal] FOREIGN KEY ([StaffRefId]) REFERENCES cdm_demo_gold.Dim1StaffPersonal ([RefId])
    ,CONSTRAINT [FKLocal_StaffList_StaffPersonal] FOREIGN KEY ([StaffLocalId]) REFERENCES cdm_demo_gold.Dim1StaffPersonal ([LocalId])
    ,CONSTRAINT [PK_StaffList] PRIMARY KEY ([StaffLocalId])
);



-- [noformat]
CREATE TABLE cdm_demo_gold.EssentialMaterials ( [EssentialMaterial] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.CensusStaff ( [StaffCohortId] VARCHAR (111)  NOT NULL , [CohortGender] VARCHAR (111)  NOT NULL , [CohortIndigenousType] VARCHAR (111)  NOT NULL , [PrimaryFTE] VARCHAR (111)  NULL , [SecondaryFTE] VARCHAR (111)  NULL , [JobFTE] VARCHAR (111)  NULL , [Headcount] bigint  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ReportingAuthority ( [Name] VARCHAR (111)  NOT NULL , [System] VARCHAR (111)  NULL , [AuthorityId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SubmittingAuthority ( [Name] VARCHAR (111)  NOT NULL , [System] VARCHAR (111)  NULL , [AuthorityId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Debtor ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [BillingName] VARCHAR (111)  NULL , [BillingNote] VARCHAR (111)  NULL , [Discount] VARCHAR (111)  NULL , [BSB] VARCHAR (111)  NULL , [AccountNumber] VARCHAR (111)  NULL , [AccountName] VARCHAR (111)  NULL , CONSTRAINT [DebtorKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.CollectionAcquittal ( [RefId] VARCHAR (111)  NOT NULL , [AuditorASICNumber] VARCHAR (111)  NULL , [Recipient] VARCHAR (111)  NULL , [Collection] VARCHAR (255)  NULL , [CollectionYear] smallint  NOT NULL , [RoundCode] VARCHAR (111)  NULL , [Declaration] VARCHAR (111)  NOT NULL , [AuditorStatement] VARCHAR (111)  NOT NULL , CONSTRAINT [CollectionAcquittalKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ChargedLocationInfo ( [RefId] VARCHAR (111)  NOT NULL , [LocationType] VARCHAR (111)  NOT NULL , [SiteCategory] VARCHAR (111)  NOT NULL , [Name] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [LocalId] VARCHAR (111)  NULL , [StateProvinceId] VARCHAR (111)  NULL , [ParentChargedLocationInfoRefId] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , CONSTRAINT [ChargedLocationInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.SubmittedBy ( [Name] VARCHAR (111)  NOT NULL , [Role] VARCHAR (111)  NULL , [Organisation] VARCHAR (111)  NULL , [Signature] VARCHAR (255)  NOT NULL , [SignatureImageType] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AGRound ( [RoundCode] VARCHAR (111)  NOT NULL , [RoundName] VARCHAR (111)  NOT NULL , [StartDate] datetime  NOT NULL , [DueDate] datetime  NOT NULL , [EndDate] datetime  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CensusStudent ( [StudentCohortId] VARCHAR (111)  NOT NULL , [CensusAge] bigint  NOT NULL , [CohortGender] VARCHAR (111)  NOT NULL , [CohortIndigenousType] VARCHAR (111)  NOT NULL , [EducationMode] VARCHAR (111)  NOT NULL , [StudentOnVisa] VARCHAR (111)  NOT NULL , [OverseasStudent] VARCHAR (111)  NOT NULL , [DisabilityLevelOfAdjustment] VARCHAR (111)  NOT NULL , [DisabilityCategory] VARCHAR (111)  NOT NULL , [FTE] VARCHAR (111)  NOT NULL , [Headcount] bigint  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CollectionStatus ( [RefId] VARCHAR (111)  NOT NULL , [ReportingAuthority] VARCHAR (111)  NOT NULL , [ReportingAuthoritySystem] VARCHAR (111)  NULL , [ReportingAuthorityCommonwealthId] VARCHAR (111)  NULL , [SubmittedBy] VARCHAR (111)  NULL , [SubmissionTimestamp] VARCHAR (255)  NULL , [AGCollection] VARCHAR (111)  NULL , [CollectionYear] smallint  NOT NULL , [RoundCode] VARCHAR (111)  NOT NULL , CONSTRAINT [CollectionStatusKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.AGRule ( [AGRuleCode] VARCHAR (111)  NULL , [AGRuleComment] VARCHAR (111)  NULL , [AGRuleResponse] VARCHAR (111)  NULL , [AGRuleStatus] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StaffActivity ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AuditedBy ( [Name] VARCHAR (111)  NOT NULL , [Role] VARCHAR (111)  NULL , [Organisation] VARCHAR (111)  NULL , [Signature] VARCHAR (255)  NOT NULL , [SignatureImageType] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CollectionDeclaration ( [RefId] VARCHAR (111)  NOT NULL , [Recipient] VARCHAR (111)  NULL , [Collection] VARCHAR (255)  NULL , [CollectionYear] smallint  NOT NULL , [RoundCode] VARCHAR (111)  NULL , [Declaration] VARCHAR (111)  NOT NULL , CONSTRAINT [CollectionDeclarationKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.CollectionRound ( [RefId] VARCHAR (111)  NOT NULL , [AGCollection] VARCHAR (111)  NULL , [CollectionYear] smallint  NOT NULL , CONSTRAINT [CollectionRoundKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.AGReportingObjectResponse ( [SubmittedRefId] VARCHAR (111)  NULL , [SIFRefId] VARCHAR (111)  NULL , [HTTPStatusCode] VARCHAR (111)  NULL , [ErrorText] VARCHAR (111)  NULL , [CommonwealthId] VARCHAR (111)  NOT NULL , [EntityName] VARCHAR (111)  NULL , [AGSubmissionStatusCode] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Activity ( [RefId] VARCHAR (111)  NOT NULL , [Title] VARCHAR (111)  NULL , [Preamble] VARCHAR (111)  NULL , [Points] bigint  NULL , [AssessmentRefId] VARCHAR (111)  NULL , [MaxAttemptsAllowed] bigint  NULL , [ActivityWeight] decimal (38, 38)  NULL , CONSTRAINT [ActivityKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.TechnicalRequirements ( [TechnicalRequirement] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SoftwareRequirement ( [SoftwareTitle] VARCHAR (111)  NOT NULL , [Version] VARCHAR (111)  NULL , [Vendor] VARCHAR (111)  NULL , [OS] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.DomainBands ( [Band1Lower] decimal (38, 38)  NOT NULL , [Band1Upper] decimal (38, 38)  NOT NULL , [Band2Lower] decimal (38, 38)  NOT NULL , [Band2Upper] decimal (38, 38)  NOT NULL , [Band3Lower] decimal (38, 38)  NOT NULL , [Band3Upper] decimal (38, 38)  NOT NULL , [Band4Lower] decimal (38, 38)  NOT NULL , [Band4Upper] decimal (38, 38)  NOT NULL , [Band5Lower] decimal (38, 38)  NOT NULL , [Band5Upper] decimal (38, 38)  NOT NULL , [Band6Lower] decimal (38, 38)  NOT NULL , [Band6Upper] decimal (38, 38)  NOT NULL , [Band7Lower] decimal (38, 38)  NOT NULL , [Band7Upper] decimal (38, 38)  NOT NULL , [Band8Lower] decimal (38, 38)  NOT NULL , [Band8Upper] decimal (38, 38)  NOT NULL , [Band9Lower] decimal (38, 38)  NOT NULL , [Band9Upper] decimal (38, 38)  NOT NULL , [Band10Lower] decimal (38, 38)  NOT NULL , [Band10Upper] decimal (38, 38)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TestletContent ( [NAPTestletLocalId] VARCHAR (111)  NOT NULL , [TestletName] VARCHAR (111)  NULL , [Node] VARCHAR (111)  NULL , [LocationInStage] bit  NULL , [TestletMaximumScore] decimal (38, 38)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.NAPEventStudentLink ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NULL , [PlatformStudentIdentifier] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolACARAId] VARCHAR (111)  NOT NULL , [NAPTestRefId] VARCHAR (111)  NULL , [NAPTestLocalId] VARCHAR (111)  NOT NULL , [SchoolSector] VARCHAR (111)  NOT NULL , [System] VARCHAR (111)  NULL , [SchoolGeolocation] VARCHAR (111)  NULL , [ReportingSchoolName] VARCHAR (111)  NULL , [NAPJurisdiction] VARCHAR (111)  NULL , [ParticipationCode] VARCHAR (111)  NOT NULL , [ParticipationText] VARCHAR (111)  NOT NULL , [Device] VARCHAR (111)  NULL , [Date] datetime  NULL , [StartTime] datetime  NULL , [LapsedTimeTest] VARCHAR (255)  NULL , [ExemptionReason] VARCHAR (111)  NULL , [PersonalDetailsChanged] bit  NULL , [PSIOtherIdMatch] bit  NULL , [PossibleDuplicate] bit  NULL , [DOBRange] bit  NULL , CONSTRAINT [NAPEventStudentLinkKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Testlet ( [NAPTestletRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.PNPCodeList ( [PNPCode] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.DomainScore ( [RawScore] decimal (38, 38)  NOT NULL , [ScaledScoreValue] decimal (38, 38)  NOT NULL , [ScaledScoreLogitValue] decimal (38, 38)  NOT NULL , [ScaledScoreStandardError] decimal (38, 38)  NOT NULL , [ScaledScoreLogitStandardError] decimal (38, 38)  NOT NULL , [StudentDomainBand] bit  NOT NULL , [StudentProficiency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.RefundAmount ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.DomainProficiency ( [Level1Lower] decimal (38, 38)  NOT NULL , [Level1Upper] decimal (38, 38)  NOT NULL , [Level2Lower] decimal (38, 38)  NOT NULL , [Level2Upper] decimal (38, 38)  NOT NULL , [Level3Lower] decimal (38, 38)  NOT NULL , [Level3Upper] decimal (38, 38)  NOT NULL , [Level4Lower] decimal (38, 38)  NOT NULL , [Level4Upper] decimal (38, 38)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TestItemContent ( [NAPTestItemLocalId] VARCHAR (111)  NOT NULL , [ItemName] VARCHAR (111)  NOT NULL , [ItemType] VARCHAR (111)  NOT NULL , [Subdomain] VARCHAR (111)  NOT NULL , [WritingGenre] VARCHAR (111)  NULL , [ItemDescriptor] VARCHAR (111)  NOT NULL , [ReleasedStatus] bit  NOT NULL , [MarkingType] VARCHAR (111)  NOT NULL , [MultipleChoiceOptionCount] int  NULL , [CorrectAnswer] VARCHAR (111)  NULL , [MaximumScore] decimal (38, 38)  NOT NULL , [ItemDifficulty] decimal (38, 38)  NOT NULL , [ItemDifficultyLogit5] decimal (38, 38)  NOT NULL , [ItemDifficultyLogit62] decimal (38, 38)  NOT NULL , [ItemDifficultyLogit5SE] decimal (38, 38)  NOT NULL , [ItemDifficultyLogit62SE] decimal (38, 38)  NOT NULL , [ItemProficiencyBand] bit  NOT NULL , [ItemProficiencyLevel] VARCHAR (111)  NULL , [ExemplarURL] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TestContent ( [NAPTestLocalId] VARCHAR (111)  NOT NULL , [TestName] VARCHAR (111)  NOT NULL , [TestType] VARCHAR (111)  NOT NULL , [Domain] VARCHAR (111)  NOT NULL , [TestYear] smallint  NOT NULL , [StagesCount] int  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.MarkValueInfo ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [Name] VARCHAR (111)  NOT NULL , [PercentageMinimum] decimal (38, 38)  NULL , [PercentageMaximum] decimal (38, 38)  NULL , [PercentagePassingGrade] decimal (38, 38)  NULL , [NumericPrecision] bigint  NULL , [NumericScale] bigint  NULL , [NumericLow] decimal (38, 38)  NULL , [NumericHigh] decimal (38, 38)  NULL , [NumericPassingGrade] decimal (38, 38)  NULL , [Narrative] VARCHAR (111)  NOT NULL , [NarrativeMaximumSize] bigint  NULL , CONSTRAINT [MarkValueInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ValidLetterMark ( [Code] VARCHAR (111)  NOT NULL , [NumericEquivalent] decimal (38, 38)  NULL , [Description] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TestItem ( [TestItemRefId] VARCHAR (111)  NOT NULL , [SequenceNumber] bit  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.NAPCodeFrame ( [RefId] VARCHAR (111)  NOT NULL , [NAPTestRefId] VARCHAR (111)  NOT NULL , CONSTRAINT [NAPCodeFrameKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.HoldInfo ( [DatePlaced] datetime  NOT NULL , [DateNeeded] datetime  NULL , [ReservationExpiry] datetime  NULL , [MadeAvailable] datetime  NULL , [Expires] datetime  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.FineAmount ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Message ( [Sent] VARCHAR (255)  NULL , [Text] VARCHAR (111)  NOT NULL , [Priority] VARCHAR (111)  NOT NULL , [PriorityCodeset] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TestLevel ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ContentDescriptionList ( [ContentDescription] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TestDisruption ( [Event] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Adjustment ( [BookletType] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.NAPStudentResponseSet ( [RefId] VARCHAR (111)  NOT NULL , [ReportExclusionFlag] bit  NOT NULL , [CalibrationSampleFlag] VARCHAR (111)  NULL , [EquatingSampleFlag] VARCHAR (111)  NULL , [PathTakenForDomain] VARCHAR (111)  NULL , [ParallelTest] VARCHAR (111)  NULL , [StudentPersonalRefId] VARCHAR (111)  NULL , [PlatformStudentIdentifier] VARCHAR (111)  NOT NULL , [NAPTestRefId] VARCHAR (111)  NULL , [NAPTestLocalId] VARCHAR (111)  NOT NULL , CONSTRAINT [NAPStudentResponseSetKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.PaymentReceipt ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [TransactionType] VARCHAR (111)  NOT NULL , [InvoiceRefId] VARCHAR (111)  NULL , [VendorInfoRefId] VARCHAR (111)  NULL , [DebtorRefId] VARCHAR (111)  NULL , [ChargedLocationInfoRefId] VARCHAR (111)  NULL , [TransactionDate] datetime  NOT NULL , [ReceivedTransactionId] VARCHAR (111)  NOT NULL , [TransactionDescription] VARCHAR (111)  NULL , [TaxRate] decimal (38, 38)  NULL , [TransactionMethod] VARCHAR (111)  NULL , [ChequeNumber] VARCHAR (111)  NULL , [TransactionNote] VARCHAR (111)  NULL , [AccountingPeriod] VARCHAR (111)  NULL , CONSTRAINT [PaymentReceiptKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.NAPTestItem ( [RefId] VARCHAR (111)  NOT NULL , CONSTRAINT [NAPTestItemKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.NAPTestScoreSummary ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolACARAId] VARCHAR (111)  NOT NULL , [NAPTestRefId] VARCHAR (111)  NULL , [NAPTestLocalId] VARCHAR (111)  NOT NULL , [DomainNationalAverage] decimal (38, 38)  NULL , [DomainSchoolAverage] decimal (38, 38)  NULL , [DomainJurisdictionAverage] decimal (38, 38)  NULL , [DomainTopNational60Percent] decimal (38, 38)  NULL , [DomainBottomNational60Percent] decimal (38, 38)  NULL , CONSTRAINT [NAPTestScoreSummaryKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ParentObjectRefId ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.NAPTest ( [RefId] VARCHAR (111)  NOT NULL , CONSTRAINT [NAPTestKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.NAPTestlet ( [RefId] VARCHAR (111)  NOT NULL , [NAPTestRefId] VARCHAR (111)  NULL , [NAPTestLocalId] VARCHAR (111)  NOT NULL , CONSTRAINT [NAPTestletKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.PersonPicture ( [RefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [OKToPublish] VARCHAR (111)  NULL , CONSTRAINT [PersonPictureKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.PublishingPermission ( [PermissionCategory] VARCHAR (111)  NOT NULL , [PermissionValue] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PersonPrivacyObligationDocument ( [RefId] VARCHAR (111)  NOT NULL , [ParentRefId] VARCHAR (111)  NOT NULL , [ParentObjectTypeName] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [StartDate] datetime  NULL , [EndDate] datetime  NULL , [ContactForRequestsRefId] VARCHAR (111)  NOT NULL , [ContactForRequestsObjectTypeName] VARCHAR (111)  NOT NULL , CONSTRAINT [PersonPrivacyObligationDocumentKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.PaymentReceiptLine ( [InvoiceRefId] VARCHAR (111)  NULL , [LocalId] VARCHAR (111)  NULL , [LocalPaymentReceiptLineId] VARCHAR (111)  NULL , [FinancialAccountRefId] VARCHAR (111)  NULL , [AccountCode] VARCHAR (111)  NULL , [TransactionDescription] VARCHAR (111)  NULL , [TaxRate] decimal (38, 38)  NULL ) ;
CREATE TABLE cdm_demo_gold.TransactionAmount ( [Currency] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PlausibleScaledValueList ( [PlausibleScaledValue] decimal (38, 38)  NULL ) ;
CREATE TABLE cdm_demo_gold.PictureSource ( [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.EquipmentInfo ( [RefId] VARCHAR (111)  NOT NULL , [Name] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [LocalId] VARCHAR (111)  NOT NULL , [AssetNumber] VARCHAR (111)  NULL , [InvoiceRefId] VARCHAR (111)  NULL , [PurchaseOrderRefId] VARCHAR (111)  NULL , [EquipmentType] VARCHAR (255)  NULL , CONSTRAINT [EquipmentInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.GradingAssignment ( [RefId] VARCHAR (111)  NOT NULL , [TeachingGroupRefId] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [GradingCategory] VARCHAR (111)  NULL , [Description] VARCHAR (111)  NOT NULL , [PointsPossible] bigint  NOT NULL , [CreateDate] datetime  NULL , [DueDate] datetime  NULL , [Weight] decimal (38, 38)  NULL , [MaxAttemptsAllowed] bit  NULL , [DetailedDescriptionURL] VARCHAR (111)  NULL , [DetailedDescriptionBinary] binary (900)  NULL , [AssessmentType] VARCHAR (111)  NULL , [LevelAssessed] VARCHAR (111)  NULL , [AssignmentPurpose] VARCHAR (111)  NULL , CONSTRAINT [GradingAssignmentKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.StudentPersonalRefIdList ( [StudentPersonalRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.FQContextualQuestion ( [FQContext] VARCHAR (111)  NOT NULL , [FQAnswer] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PrerequisiteList ( [Prerequisite] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.FinancialAccount ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [ParentAccountRefId] VARCHAR (111)  NULL , [ChargedLocationInfoRefId] VARCHAR (111)  NULL , [AccountNumber] VARCHAR (111)  NOT NULL , [Name] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [ClassType] VARCHAR (111)  NOT NULL , [AccountCode] VARCHAR (111)  NULL , [CreationDate] datetime  NOT NULL , [CreationTime] datetime  NOT NULL , CONSTRAINT [FinancialAccountKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.LearningStandard ( [LearningStandardItemRefId] VARCHAR (111)  NULL , [LearningStandardURL] VARCHAR (111)  NULL , [LearningStandardLocalId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.GradingAssignmentScore ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NULL , [StudentPersonalLocalId] VARCHAR (111)  NOT NULL , [TeachingGroupRefId] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [GradingAssignmentRefId] VARCHAR (111)  NOT NULL , [StaffPersonalRefId] VARCHAR (111)  NULL , [DateGraded] datetime  NULL , [ExpectedScore] bit  NULL , [ScorePoints] bigint  NULL , [ScorePercent] decimal (38, 38)  NULL , [ScoreLetter] VARCHAR (111)  NULL , [ScoreDescription] VARCHAR (111)  NULL , [TeacherJudgement] VARCHAR (111)  NULL , [MarkInfoRefId] VARCHAR (111)  NULL , [AssignmentScoreIteration] VARCHAR (111)  NULL , CONSTRAINT [GradingAssignmentScoreKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.SubAssignmentList ( [GradingAssignmentRefId] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ScoreDescription ( [ScoreValue] decimal (38, 38)  NOT NULL , [Descriptor] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.BilledEntity ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Score ( [MaxScoreValue] decimal (38, 38)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.FinancialQuestionnaireCollection ( [RefId] VARCHAR (111)  NOT NULL , [FQYear] smallint  NOT NULL , [RoundCode] VARCHAR (111)  NOT NULL , CONSTRAINT [FinancialQuestionnaireCollectionKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.RubricScoringGuide ( [RubricType] VARCHAR (111)  NOT NULL , [Descriptor] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Subscore ( [SubscoreType] VARCHAR (111)  NOT NULL , [SubscoreValue] decimal (38, 38)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.FQReporting ( [CommonwealthId] VARCHAR (111)  NOT NULL , [EntityName] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.FQItem ( [FQItemCode] VARCHAR (111)  NOT NULL , [TuitionAmount] decimal (38, 38)  NULL , [BoardingAmount] decimal (38, 38)  NULL , [SystemAmount] decimal (38, 38)  NULL , [DioceseAmount] decimal (38, 38)  NULL , [FQComments] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SIF_RefId ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PurchasingItem ( [ItemNumber] VARCHAR (111)  NULL , [ItemDescription] VARCHAR (111)  NOT NULL , [LocalItemId] VARCHAR (111)  NULL , [Quantity] VARCHAR (111)  NULL , [QuantityDelivered] VARCHAR (111)  NULL , [CancelledOrder] VARCHAR (111)  NULL , [TaxRate] decimal (38, 38)  NULL ) ;
CREATE TABLE cdm_demo_gold.IdentityAssertion ( [SchemaName] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Invoice ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [FormNumber] VARCHAR (111)  NULL , [BillingDate] datetime  NOT NULL , [TransactionDescription] VARCHAR (111)  NOT NULL , [Ledger] VARCHAR (111)  NOT NULL , [ChargedLocationInfoRefId] VARCHAR (111)  NULL , [TaxRate] decimal (38, 38)  NULL , [TaxType] VARCHAR (111)  NULL , [CreatedBy] VARCHAR (111)  NULL , [ApprovedBy] VARCHAR (111)  NULL , [ItemDetail] VARCHAR (111)  NULL , [DueDate] datetime  NULL , [AccountingPeriod] VARCHAR (111)  NULL , [RelatedPurchaseOrderRefId] VARCHAR (111)  NULL , [Voluntary] VARCHAR (111)  NULL , CONSTRAINT [InvoiceKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.InvoicedEntity ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.NetAmount ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.AccountCodeList ( [AccountCode] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TotalCost ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Identity ( [RefId] VARCHAR (111)  NOT NULL , [AuthenticationSource] VARCHAR (111)  NOT NULL , [AuthenticationSourceGlobalUID] VARCHAR (111)  NULL , CONSTRAINT [IdentityKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.TaxAmount ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.UnitCost ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ExpenseAccount ( [AccountCode] VARCHAR (111)  NOT NULL , [FinancialAccountRefId] VARCHAR (111)  NULL , [AccountingPeriod] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Journal ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [DebitFinancialAccountRefId] VARCHAR (111)  NULL , [CreditFinancialAccountRefId] VARCHAR (111)  NULL , [DebitAccountCode] VARCHAR (111)  NULL , [CreditAccountCode] VARCHAR (111)  NULL , [GSTCodeOriginal] VARCHAR (111)  NULL , [GSTCodeReplacement] VARCHAR (111)  NULL , [Note] VARCHAR (111)  NULL , [CreatedDate] datetime  NULL , [ApprovedDate] datetime  NULL , [CreatedBy] VARCHAR (111)  NULL , [ApprovedBy] VARCHAR (111)  NULL , CONSTRAINT [JournalKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.JournalAdjustment ( [DebitFinancialAccountRefId] VARCHAR (111)  NULL , [CreditFinancialAccountRefId] VARCHAR (111)  NULL , [DebitAccountCode] VARCHAR (111)  NULL , [CreditAccountCode] VARCHAR (111)  NULL , [GSTCodeOriginal] VARCHAR (111)  NULL , [GSTCodeReplacement] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.FinancialAccountRefIdList ( [FinancialAccountRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Password ( [Algorithm] VARCHAR (111)  NOT NULL , [KeyName] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Amount ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.OriginatingTransactionRefId ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.BilledAmount ( [Currency] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LineAdjustmentAmount ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SessionInfo ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [TimeTableCellRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [LocalId] VARCHAR (111)  NOT NULL , [TimeTableSubjectLocalId] VARCHAR (111)  NOT NULL , [TeachingGroupLocalId] VARCHAR (111)  NOT NULL , [SchoolLocalId] VARCHAR (111)  NULL , [StaffPersonalLocalId] VARCHAR (111)  NULL , [RoomNumber] VARCHAR (111)  NULL , [DayId] VARCHAR (111)  NOT NULL , [PeriodId] VARCHAR (111)  NOT NULL , [SessionDate] datetime  NOT NULL , [StartTime] datetime  NULL , [FinishTime] datetime  NULL , [RollMarked] VARCHAR (111)  NULL , CONSTRAINT [SessionInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Demographics ( [IndigenousStatus] VARCHAR (111)  NULL , [Gender] VARCHAR (111)  NULL , [Sex] VARCHAR (111)  NULL , [BirthDate] datetime  NULL , [DateOfDeath] datetime  NULL , [Deceased] VARCHAR (111)  NULL , [BirthDateVerification] VARCHAR (111)  NULL , [PlaceOfBirth] VARCHAR (111)  NULL , [StateOfBirth] VARCHAR (255)  NULL , [CountryOfBirth] VARCHAR (111)  NULL , [CountryArrivalDate] datetime  NULL , [AustralianCitizenshipStatus] VARCHAR (111)  NULL , [ReligiousRegion] VARCHAR (111)  NULL , [PermanentResident] VARCHAR (111)  NULL , [VisaSubClass] VARCHAR (255)  NULL , [VisaStatisticalCode] VARCHAR (111)  NULL , [VisaNumber] VARCHAR (111)  NULL , [VisaGrantDate] datetime  NULL , [VisaExpiryDate] datetime  NULL , [VisaConditions] VARCHAR (111)  NULL , [VisaStudyEntitlement] VARCHAR (111)  NULL , [LBOTE] VARCHAR (111)  NULL , [InterpreterRequired] VARCHAR (111)  NULL , [ImmunisationCertificateStatus] VARCHAR (111)  NULL , [CulturalBackground] VARCHAR (111)  NULL , [MaritalStatus] VARCHAR (111)  NULL , [MedicareNumber] VARCHAR (111)  NULL , [MedicarePositionNumber] VARCHAR (111)  NULL , [MedicareCardHolder] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.LocationOfInstruction ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.HouseholdContactInfo ( [PreferenceNumber] bigint  NULL , [HouseholdContactId] VARCHAR (111)  NULL , [HouseholdSalutation] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ReligiousEvent ( [Type] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StudentActivityType ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Language ( [Code] VARCHAR (111)  NOT NULL , [LanguageType] VARCHAR (111)  NULL , [Dialect] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SchoolCourseInfoOverride ( [CourseCode] VARCHAR (111)  NULL , [StateCourseCode] VARCHAR (111)  NULL , [DistrictCourseCode] VARCHAR (111)  NULL , [CourseTitle] VARCHAR (111)  NULL , [InstructionalLevel] VARCHAR (111)  NULL , [CourseCredits] VARCHAR (111)  NULL , [Override] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.MediumOfInstruction ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LanguageOfInstruction ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CountriesOfResidency ( [CountryOfResidency] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CountriesOfCitizenship ( [CountryOfCitizenship] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.EnglishProficiency ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.SectionInfo ( [RefId] VARCHAR (111)  NOT NULL , [SchoolCourseInfoRefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [SchoolYear] smallint  NULL , [TermInfoRefId] VARCHAR (111)  NULL , [SummerSchool] VARCHAR (111)  NULL , [CourseSectionCode] VARCHAR (111)  NULL , [SectionCode] VARCHAR (111)  NULL , [CountForAttendance] VARCHAR (111)  NULL , CONSTRAINT [SectionInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.StaffAssignment ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NULL , [StaffPersonalRefId] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [PrimaryAssignment] VARCHAR (111)  NOT NULL , [JobStartDate] datetime  NULL , [JobEndDate] datetime  NULL , [JobFTE] VARCHAR (111)  NULL , [JobFunction] VARCHAR (111)  NULL , [EmploymentStatus] VARCHAR (111)  NULL , [CasualReliefTeacher] VARCHAR (111)  NULL , [Homegroup] VARCHAR (111)  NULL , [House] VARCHAR (111)  NULL , [PreviousSchoolName] VARCHAR (111)  NULL , [AvailableForTimetable] VARCHAR (111)  NULL , CONSTRAINT [StaffAssignmentKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.CalendarSummaryList ( [CalendarSummaryRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Religion ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StaffSubject ( [PreferenceNumber] bigint  NOT NULL , [SubjectLocalId] VARCHAR (111)  NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.DwellingArrangement ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.VisaSubClass ( [Code] VARCHAR (255)  NOT NULL , [VisaExpiryDate] datetime  NULL , [ATEExpiryDate] datetime  NULL , [ATEStartDate] datetime  NULL , [VisaStatisticalCode] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Passport ( [Number] VARCHAR (111)  NOT NULL , [ExpiryDate] datetime  NULL , [Country] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PrivateHealthInsurance ( [Company] VARCHAR (111)  NOT NULL , [Number] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.MostRecent ( [SchoolLocalId] VARCHAR (111)  NULL , [SchoolACARAId] VARCHAR (111)  NULL , [LocalCampusId] VARCHAR (111)  NULL , [HomeGroup] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.NAPLANClassList ( [ClassCode] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentActivityInfo ( [RefId] VARCHAR (111)  NOT NULL , [Title] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [StudentActivityLevel] VARCHAR (111)  NULL , [CurricularStatus] VARCHAR (111)  NULL , CONSTRAINT [StudentActivityInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.StudentAttendanceCollection ( [RefId] VARCHAR (111)  NOT NULL , [StudentAttendanceCollectionYear] smallint  NOT NULL , [RoundCode] VARCHAR (111)  NOT NULL , CONSTRAINT [StudentAttendanceCollectionKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.StudentAttendanceCollectionReporting ( [CommonwealthId] VARCHAR (111)  NOT NULL , [EntityName] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.CohortYearLevel ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StatsCohort ( [StatsCohortId] VARCHAR (111)  NOT NULL , [StatsIndigenousStudentType] VARCHAR (111)  NOT NULL , [CohortGender] VARCHAR (111)  NOT NULL , [DaysInReferencePeriod] bigint  NOT NULL , [PossibleSchoolDays] bigint  NOT NULL , [AttendanceDays] VARCHAR (111)  NOT NULL , [AttendanceLess90Percent] bigint  NOT NULL , [AttendanceGTE90Percent] bigint  NOT NULL , [PossibleSchoolDaysGT90PercentAttendance] bigint  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StudentActivityParticipation ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [StudentActivityInfoRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NULL , [ParticipationComment] VARCHAR (111)  NULL , [StartDate] datetime  NULL , [EndDate] datetime  NULL , [Role] VARCHAR (111)  NULL , CONSTRAINT [StudentActivityParticipationKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.StudentAttendanceSummary ( [StudentAttendanceSummaryRefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [StartDate] datetime  NOT NULL , [EndDate] datetime  NOT NULL , [StartDay] bigint  NULL , [EndDay] bigint  NULL , [FTE] VARCHAR (111)  NULL , [DaysAttended] decimal (38, 38)  NOT NULL , [ExcusedAbsences] decimal (38, 38)  NOT NULL , [UnexcusedAbsences] decimal (38, 38)  NOT NULL , [DaysTardy] decimal (38, 38)  NULL , [DaysInMembership] decimal (38, 38)  NOT NULL , CONSTRAINT [StudentAttendanceSummaryKey1] PRIMARY KEY ( [StudentAttendanceSummaryRefId] ) ) ;
CREATE TABLE cdm_demo_gold.AttendanceCode ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StudentAttendanceTimeList ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL , [SchoolYear] smallint  NOT NULL , CONSTRAINT [StudentAttendanceTimeListKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.RecognitionList ( [Recognition] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AttendanceTime ( [AttendanceType] VARCHAR (111)  NULL , [AttendanceStatus] VARCHAR (111)  NOT NULL , [StartTime] datetime  NOT NULL , [EndTime] datetime  NOT NULL , [DurationValue] decimal (38, 38)  NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL , [AttendanceNote] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.PeriodAttendance ( [AttendanceType] VARCHAR (111)  NULL , [AttendanceStatus] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL , [SessionInfoRefId] VARCHAR (111)  NULL , [ScheduledActivityRefId] VARCHAR (111)  NULL , [TimetablePeriod] VARCHAR (111)  NULL , [DayId] VARCHAR (111)  NULL , [StartTime] datetime  NULL , [EndTime] datetime  NULL , [TimeIn] datetime  NULL , [TimeOut] datetime  NULL , [TimeTableCellRefId] VARCHAR (111)  NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL , [AttendanceNote] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Strategies ( [Strategy] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.BinaryData ( [MIMEType] VARCHAR (111)  NOT NULL , [FileName] VARCHAR (111)  NULL , [Description] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Organizations ( [Organization] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Copyright ( [Date] datetime  NULL , [Holder] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StandardSettingBody ( [Country] VARCHAR (111)  NULL , [StateProvince] VARCHAR (255)  NULL , [SettingBodyName] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ACStrandSubjectArea ( [ACStrand] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ContactInfo ( [PositionTitle] VARCHAR (111)  NULL , [Role] VARCHAR (111)  NULL , [RegistrationDetails] VARCHAR (111)  NULL , [Qualifications] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TextData ( [MIMEType] VARCHAR (111)  NULL , [FileName] VARCHAR (111)  NULL , [Description] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.RichDescription ( [RefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.LEAInfo ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NOT NULL , [StateProvinceId] VARCHAR (111)  NULL , [CommonwealthId] VARCHAR (111)  NULL , [LEAName] VARCHAR (111)  NOT NULL , [LEAURL] VARCHAR (111)  NULL , [OperationalStatus] VARCHAR (111)  NULL , [JurisdictionLowerHouse] VARCHAR (111)  NULL , [SLA] VARCHAR (111)  NULL , CONSTRAINT [LEAInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Approval ( [Organization] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LearningResource ( [RefId] VARCHAR (111)  NOT NULL , [Name] VARCHAR (111)  NOT NULL , [Author] VARCHAR (111)  NULL , [Status] VARCHAR (111)  NULL , [Description] VARCHAR (111)  NULL , [UseAgreement] VARCHAR (111)  NULL , [AgreementDate] datetime  NULL , [LearningResourcePackageRefId] VARCHAR (111)  NULL , CONSTRAINT [LearningResourceKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.LEAContact ( [PublishInDirectory] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.AssociatedObject ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.XMLData ( [Description] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.MediaTypes ( [MediaType] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Reference ( [URL] VARCHAR (111)  NOT NULL , [MIMEType] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.EducationAgencyType ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Component ( [Name] VARCHAR (111)  NOT NULL , [Reference] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.LearningResourcePackage ( [RefId] VARCHAR (111)  NOT NULL , CONSTRAINT [LearningResourcePackageKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.LearningStandardDocument ( [RefId] VARCHAR (111)  NOT NULL , [Title] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [Source] VARCHAR (111)  NOT NULL , [OrganizationContactPoint] VARCHAR (111)  NULL , [DocumentStatus] VARCHAR (111)  NOT NULL , [DocumentDate] datetime  NULL , [LocalAdoptionDate] datetime  NULL , [LocalArchiveDate] datetime  NULL , [EndOfLifeDate] datetime  NULL , [RepositoryDate] datetime  NULL , [LearningStandardItemRefId] VARCHAR (111)  NOT NULL , CONSTRAINT [LearningStandardDocumentKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Authors ( [Author] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.RelatedLearningStandards ( [LearningStandardDocumentRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.LearningStandardItem ( [RefId] VARCHAR (111)  NOT NULL , [LearningStandardDocumentRefId] VARCHAR (111)  NOT NULL , [Level4] VARCHAR (111)  NULL , [Level5] VARCHAR (111)  NULL , CONSTRAINT [LearningStandardItemKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.LearningResourceRefId ( [ResourceType] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StandardHierarchyLevel ( [Number] bigint  NOT NULL , [Description] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AlternateIdentificationCodes ( [AlternateIdentificationCode] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Statements ( [Statement] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PatronName ( [Title] VARCHAR (111)  NULL , [FamilyName] VARCHAR (111)  NULL , [GivenName] VARCHAR (111)  NULL , [MiddleName] VARCHAR (111)  NULL , [FamilyNameFirst] VARCHAR (111)  NULL , [PreferredFamilyName] VARCHAR (111)  NULL , [PreferredFamilyNameFirst] VARCHAR (111)  NULL , [PreferredGivenName] VARCHAR (111)  NULL , [Suffix] VARCHAR (111)  NULL , [FullName] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LibraryPatronStatus ( [RefId] VARCHAR (111)  NOT NULL , [LibraryType] VARCHAR (111)  NOT NULL , [PatronRefId] VARCHAR (111)  NULL , [PatronLocalId] VARCHAR (111)  NULL , [PatronRefObject] VARCHAR (111)  NOT NULL , [NumberOfCheckouts] bigint  NOT NULL , [NumberOfHoldItems] bigint  NULL , [NumberOfOverdues] bigint  NULL , [NumberOfFines] bigint  NULL , [NumberOfRefunds] bigint  NULL , CONSTRAINT [LibraryPatronStatusKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.CheckoutInfo ( [CheckedOutOn] VARCHAR (255)  NOT NULL , [ReturnBy] VARCHAR (255)  NOT NULL , [RenewalCount] bigint  NULL ) ;
CREATE TABLE cdm_demo_gold.FineInfo ( [Assessed] VARCHAR (255)  NOT NULL , [Description] VARCHAR (111)  NULL , [Reference] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StandardIdentifier ( [YearCreated] smallint  NOT NULL , [StandardNumber] VARCHAR (111)  NOT NULL , [Benchmark] VARCHAR (111)  NULL , [IndicatorNumber] VARCHAR (111)  NULL , [Organization] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ElectronicId ( [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PredecessorItems ( [LearningStandardItemRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ItemInfo ( [Title] VARCHAR (111)  NOT NULL , [Author] VARCHAR (111)  NULL , [CallNumber] VARCHAR (111)  NULL , [ISBN] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Cost ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StatementCodes ( [StatementCode] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ReplacementCost ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.LearningStandardItemRefId ( [RelationshipType] VARCHAR (255)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LearningObjectives ( [LearningObjective] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Creator ( [Name] VARCHAR (111)  NOT NULL , [ID] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.SoftwareVendorInfo ( [SoftwareProduct] VARCHAR (111)  NOT NULL , [SoftwareVersion] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Modified ( [By] VARCHAR (111)  NOT NULL , [DateTime] VARCHAR (255)  NOT NULL , [Description] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SIF_ExtendedElement ( [Name] VARCHAR (111)  NOT NULL , [SIF_Action] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.AddressCollectionReporting ( [CommonwealthId] VARCHAR (111)  NOT NULL , [EntityName] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.EntityContact ( [PositionTitle] VARCHAR (111)  NULL , [Role] VARCHAR (111)  NULL , [RegistrationDetails] VARCHAR (111)  NULL , [Qualifications] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Name ( [Title] VARCHAR (111)  NULL , [FamilyName] VARCHAR (111)  NULL , [GivenName] VARCHAR (111)  NULL , [MiddleName] VARCHAR (111)  NULL , [FamilyNameFirst] VARCHAR (111)  NULL , [PreferredFamilyName] VARCHAR (111)  NULL , [PreferredFamilyNameFirst] VARCHAR (111)  NULL , [PreferredGivenName] VARCHAR (111)  NULL , [Suffix] VARCHAR (111)  NULL , [FullName] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Address ( [EffectiveFromDate] datetime  NULL , [EffectiveToDate] datetime  NULL , [City] VARCHAR (111)  NOT NULL , [StateProvince] VARCHAR (255)  NULL , [Country] VARCHAR (111)  NULL , [PostalCode] VARCHAR (111)  NOT NULL , [RadioContact] VARCHAR (111)  NULL , [Community] VARCHAR (111)  NULL , [LocalId] VARCHAR (111)  NULL , [AddressGlobalUID] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL , [Role] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AddressCollection ( [RefId] VARCHAR (111)  NOT NULL , [AddressCollectionYear] smallint  NOT NULL , [RoundCode] VARCHAR (111)  NOT NULL , CONSTRAINT [AddressCollectionKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Students ( [StudentPersonalRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.OtherCode ( [Codeset] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.SubjectArea ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LearningStandards ( [LearningStandardItemRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Prerequisites ( [Prerequisite] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentContactRelationship ( [StudentContactRelationshipRefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [StudentContactPersonalRefId] VARCHAR (111)  NOT NULL , [ParentRelationshipStatus] VARCHAR (111)  NULL , [MainlySpeaksEnglishAtHome] VARCHAR (111)  NULL , [ContactSequence] bigint  NULL , [ContactSequenceSource] VARCHAR (111)  NULL , [ContactMethod] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , CONSTRAINT [StudentContactRelationshipKey1] PRIMARY KEY ( [StudentContactRelationshipRefId] ) ) ;
CREATE TABLE cdm_demo_gold.DisabilityCategoryConsideredList ( [DisabilityCategoryConsidered] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ArrivalSchool ( [ACARAId] VARCHAR (111)  NULL , [Name] VARCHAR (111)  NULL , [City] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.HouseholdList ( [Household] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ContactFlags ( [ParentLegalGuardian] VARCHAR (111)  NULL , [PickupRights] VARCHAR (111)  NULL , [LivesWith] VARCHAR (111)  NULL , [AccessToRecords] VARCHAR (111)  NULL , [ReceivesAssessmentReport] VARCHAR (111)  NULL , [EmergencyContact] VARCHAR (111)  NULL , [HasCustody] VARCHAR (111)  NULL , [DisciplinaryContact] VARCHAR (111)  NULL , [AttendanceContact] VARCHAR (111)  NULL , [PrimaryCareProvider] VARCHAR (111)  NULL , [FeesBilling] VARCHAR (111)  NULL , [FeesAccess] VARCHAR (111)  NULL , [FamilyMail] VARCHAR (111)  NULL , [InterventionOrder] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.FeePercentage ( [Curriculum] decimal (38, 38)  NULL , [Other] decimal (38, 38)  NULL ) ;
CREATE TABLE cdm_demo_gold.VisaStatus ( [Code] VARCHAR (255)  NOT NULL , [VisaExpiryDate] datetime  NULL , [ATEExpiryDate] datetime  NULL , [ATEStartDate] datetime  NULL , [VisaStatisticalCode] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SupportNeeds ( [NegotiatedCurriculumPlan] VARCHAR (111)  NULL , [AdjustedEducationProgram] VARCHAR (111)  NULL , [CareerGuidanceFileHeld] VARCHAR (111)  NULL , [SchoolCounsellorFileHeld] VARCHAR (111)  NULL , [OtherLearningSupport] VARCHAR (111)  NULL , [OtherLearningSupportText] VARCHAR (111)  NULL , [AcceleratedProgram] VARCHAR (111)  NULL , [YoungCarersRole] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentDataTransferNote ( [RefId] VARCHAR (111)  NOT NULL , [RequestID] VARCHAR (111)  NULL , [Gender] VARCHAR (111)  NULL , [BirthDate] datetime  NOT NULL , [PlaceOfBirth] VARCHAR (111)  NULL , [StateOfBirth] VARCHAR (255)  NULL , [CountryOfBirth] VARCHAR (111)  NOT NULL , [AustralianCitizenship] bit  NULL , [FollowupRequest] bit  NULL , [ChildSubjectToOrders] bit  NULL , [Attendance] bit  NULL , [Healthcare] bit  NULL , [InterestTalents] VARCHAR (111)  NULL , [DisciplinaryAbsences] bit  NULL , [IndividualBehaviourManagementPlan] bit  NULL , [NationalUniqueStudentIdentifier] VARCHAR (111)  NULL , [IndigenousStatus] VARCHAR (111)  NULL , [LBOTE] bit  NULL , [LatestReportAvailable] bit  NULL , [AdditionalNotes] VARCHAR (111)  NULL , [Consent] bit  NULL , CONSTRAINT [StudentDataTransferNoteKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.StudentDailyAttendance ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL , [SchoolYear] smallint  NOT NULL , [DayValue] VARCHAR (111)  NULL , [AttendanceStatus] VARCHAR (111)  NOT NULL , [TimeIn] datetime  NULL , [TimeOut] datetime  NULL , [AbsenceValue] decimal (38, 38)  NULL , [AttendanceNote] VARCHAR (111)  NULL , CONSTRAINT [StudentDailyAttendanceKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.NAPLANScore ( [Domain] VARCHAR (111)  NOT NULL , [ParticipationCode] VARCHAR (111)  NULL , [TestYear] smallint  NULL ) ;
CREATE TABLE cdm_demo_gold.WorkingWithChildrenCheck ( [StateTerritory] VARCHAR (255)  NOT NULL , [Number] VARCHAR (111)  NOT NULL , [HolderName] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NULL , [Reasons] VARCHAR (111)  NULL , [Determination] VARCHAR (111)  NULL , [CheckDate] datetime  NULL , [DeterminationDate] datetime  NULL , [ExpiryDate] datetime  NULL ) ;
CREATE TABLE cdm_demo_gold.AuditInfo ( [CreationDateTime] VARCHAR (255)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PreviousSchool ( [ACARAId] VARCHAR (111)  NULL , [Name] VARCHAR (111)  NOT NULL , [City] VARCHAR (111)  NOT NULL , [State] VARCHAR (255)  NULL , [Sector] VARCHAR (111)  NULL , [System] VARCHAR (111)  NULL , [ExitReason] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Marker ( [StaffPersonalRefId] VARCHAR (111)  NULL , [Role] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentContactPersonal ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [EmploymentType] VARCHAR (111)  NULL , [SchoolEducationalLevel] VARCHAR (111)  NULL , [NonSchoolEducation] VARCHAR (111)  NULL , [Employment] VARCHAR (111)  NULL , [Workplace] VARCHAR (111)  NULL , CONSTRAINT [StudentContactPersonalKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Relationship ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.DepartureSchool ( [ACARAId] VARCHAR (111)  NULL , [Name] VARCHAR (111)  NOT NULL , [City] VARCHAR (111)  NOT NULL , [State] VARCHAR (255)  NULL , [Sector] VARCHAR (111)  NULL , [System] VARCHAR (111)  NULL , [StartedAtSchoolDate] datetime  NULL , [ExitDate] datetime  NULL ) ;
CREATE TABLE cdm_demo_gold.NCCD ( [LevelOfAdjustment] VARCHAR (111)  NOT NULL , [CategoryOfDisability] VARCHAR (111)  NULL , [DateOfAssessment] datetime  NULL ) ;
CREATE TABLE cdm_demo_gold.EducationalAssessment ( [Name] VARCHAR (111)  NOT NULL , [Content] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentGrade ( [Subject] VARCHAR (111)  NULL , [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [Homegroup] VARCHAR (111)  NULL , [TeachingGroupShortName] VARCHAR (111)  NULL , [TeachingGroupRefId] VARCHAR (111)  NULL , [StaffPersonalRefId] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [TermInfoRefId] VARCHAR (111)  NULL , [Description] VARCHAR (111)  NULL , [TeacherJudgement] VARCHAR (111)  NULL , [TermSpan] VARCHAR (111)  NULL , [SchoolYear] smallint  NULL ) ;
CREATE TABLE cdm_demo_gold.LearningArea ( [ACStrand] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Grade ( [Percentage] decimal (38, 38)  NULL , [Numeric] decimal (38, 38)  NULL , [Letter] VARCHAR (111)  NULL , [ProgressLevel] VARCHAR (111)  NULL , [Narrative] VARCHAR (111)  NULL , [MarkInfoRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.STDNAttachment ( [FileName] VARCHAR (111)  NOT NULL , [Field] VARCHAR (111)  NULL , [Description] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentParticipation ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [StudentParticipationAsOfDate] datetime  NOT NULL , [ProgramType] VARCHAR (111)  NULL , [ReferralDate] datetime  NULL , [GiftedEligibilityCriteria] VARCHAR (111)  NULL , [EvaluationParentalConsentDate] datetime  NULL , [EvaluationDate] datetime  NULL , [EvaluationExtensionDate] datetime  NULL , [ExtensionComments] VARCHAR (111)  NULL , [ReevaluationDate] datetime  NULL , [ProgramEligibilityDate] datetime  NULL , [ProgramPlanDate] datetime  NULL , [ProgramPlanEffectiveDate] datetime  NULL , [NOREPDate] datetime  NULL , [PlacementParentalConsentDate] datetime  NULL , [ProgramPlacementDate] datetime  NULL , [ExtendedSchoolYear] bit  NULL , [ExtendedDay] bit  NULL , [EntryPerson] VARCHAR (111)  NULL , [StudentSpecialEducationFTE] VARCHAR (111)  NULL , [ParticipationContact] VARCHAR (111)  NULL , CONSTRAINT [StudentParticipationKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ManagingSchool ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ReferralSource ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ProgramAvailability ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ProgramFundingSource ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StudentPeriodAttendance ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL , [SessionInfoRefId] VARCHAR (111)  NULL , [ScheduledActivityRefId] VARCHAR (111)  NULL , [TimetablePeriod] VARCHAR (111)  NULL , [TimeIn] datetime  NULL , [TimeOut] datetime  NULL , [AttendanceStatus] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NULL , [AttendanceComment] VARCHAR (111)  NULL , CONSTRAINT [StudentPeriodAttendanceKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ProgramStatus ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CreationUser ( [UserId] VARCHAR (111)  NOT NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AlertMessage ( [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.MedicalAlertMessage ( [Severity] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StudentPersonal ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NOT NULL , [StateProvinceId] VARCHAR (111)  NULL , [NationalUniqueStudentIdentifier] VARCHAR (111)  NULL , [ProjectedGraduationYear] smallint  NULL , [OnTimeGraduationYear] smallint  NULL , [GraduationDate] VARCHAR (255)  NULL , [AcceptableUsePolicy] VARCHAR (111)  NULL , [GiftedTalented] VARCHAR (111)  NULL , [EconomicDisadvantage] VARCHAR (111)  NULL , [ESL] VARCHAR (111)  NULL , [ESLDateAssessed] datetime  NULL , [YoungCarersRole] VARCHAR (111)  NULL , [Disability] VARCHAR (111)  NULL , [CategoryOfDisability] VARCHAR (111)  NULL , [IntegrationAide] VARCHAR (111)  NULL , [EducationSupport] VARCHAR (111)  NULL , [HomeSchooledStudent] VARCHAR (111)  NULL , [IndependentStudent] VARCHAR (111)  NULL , [Sensitive] VARCHAR (111)  NULL , [OfflineDelivery] VARCHAR (111)  NULL , [ESLSupport] VARCHAR (111)  NULL , [PrePrimaryEducation] VARCHAR (111)  NULL , [PrePrimaryEducationHours] VARCHAR (111)  NULL , [FirstAUSchoolEnrollment] datetime  NULL , CONSTRAINT [StudentPersonalKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.StudentSchoolEnrollment ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [MembershipType] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [TimeFrame] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [IntendedEntryDate] datetime  NULL , [EntryDate] datetime  NOT NULL , [Homegroup] VARCHAR (111)  NULL , [ACARASchoolId] VARCHAR (111)  NULL , [ClassCode] VARCHAR (111)  NULL , [ReportingSchool] VARCHAR (111)  NULL , [House] VARCHAR (111)  NULL , [IndividualLearningPlan] VARCHAR (111)  NULL , [ExitDate] datetime  NULL , [FTE] VARCHAR (111)  NULL , [FTPTStatus] VARCHAR (111)  NULL , [FFPOS] VARCHAR (111)  NULL , [RecordClosureReason] VARCHAR (111)  NULL , [PreviousSchool] VARCHAR (111)  NULL , [PreviousSchoolName] VARCHAR (111)  NULL , [DestinationSchool] VARCHAR (111)  NULL , [DestinationSchoolName] VARCHAR (111)  NULL , [StartedAtSchoolDate] datetime  NULL , [DisabilityLevelOfAdjustment] VARCHAR (111)  NULL , [DisabilityCategory] VARCHAR (111)  NULL , [CensusAge] bigint  NULL , [DistanceEducationStudent] VARCHAR (111)  NULL , [BoardingStatus] VARCHAR (111)  NULL , [InternationalStudent] VARCHAR (111)  NULL , CONSTRAINT [StudentSchoolEnrollmentKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.EntryType ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Homeroom ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Advisor ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Counselor ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Calendar ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.FromSchool ( [TravelMode] VARCHAR (111)  NULL , [TravelDetails] VARCHAR (111)  NULL , [TravelAccompaniment] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TermInfo ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [StartDate] datetime  NOT NULL , [EndDate] datetime  NOT NULL , [Description] VARCHAR (111)  NULL , [RelativeDuration] VARCHAR (111)  NULL , [TermCode] VARCHAR (111)  NULL , [Track] VARCHAR (111)  NULL , [TermSpan] VARCHAR (111)  NULL , [MarkingTerm] VARCHAR (111)  NULL , [SchedulingTerm] VARCHAR (111)  NULL , [AttendanceTerm] VARCHAR (111)  NULL , CONSTRAINT [TermInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.TeachingGroupPeriod ( [TimeTableCellRefId] VARCHAR (111)  NULL , [RoomNumber] VARCHAR (111)  NULL , [StaffLocalId] VARCHAR (111)  NULL , [DayId] VARCHAR (111)  NOT NULL , [PeriodId] VARCHAR (111)  NULL , [StartTime] datetime  NULL , [CellType] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudyDescription ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AcademicYear ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StudentScoreJudgementAgainstStandard ( [RefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [TermInfoRefId] VARCHAR (111)  NULL , [LocalTermCode] VARCHAR (111)  NULL , [StudentPersonalRefId] VARCHAR (111)  NULL , [StudentStateProvinceId] VARCHAR (111)  NULL , [StudentLocalId] VARCHAR (111)  NULL , [TeachingGroupRefId] VARCHAR (111)  NULL , [ClassLocalId] VARCHAR (111)  NULL , [StaffPersonalRefId] VARCHAR (111)  NULL , [StaffLocalId] VARCHAR (111)  NULL , [CurriculumCode] VARCHAR (111)  NULL , [CurriculumNodeCode] VARCHAR (111)  NULL , [Score] VARCHAR (111)  NOT NULL , [TeacherJudgement] VARCHAR (111)  NULL , [SpecialCircumstanceLocalCode] VARCHAR (111)  NULL , [ManagedPathwayLocalCode] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolLocalId] VARCHAR (111)  NULL , [SchoolCommonwealthId] VARCHAR (111)  NULL , CONSTRAINT [StudentScoreJudgementAgainstStandardKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.TimeTableScheduleCell ( [TimeTableScheduleCellLocalId] VARCHAR (111)  NOT NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL , [TeachingGroupGUID] VARCHAR (111)  NOT NULL , [RoomInfoRefId] VARCHAR (111)  NULL , [StaffPersonalRefId] VARCHAR (111)  NULL , [TimeTableLocalId] VARCHAR (111)  NULL , [SubjectLocalId] VARCHAR (111)  NULL , [TeachingGroupLocalId] VARCHAR (111)  NULL , [RoomNumber] VARCHAR (111)  NULL , [StaffLocalId] VARCHAR (111)  NULL , [DayId] VARCHAR (111)  NOT NULL , [PeriodId] VARCHAR (111)  NOT NULL , [CellType] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolLocalId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ExitType ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ExitStatus ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PromotionInfo ( [PromotionStatus] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.CatchmentStatus ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TeachingGroup ( [RefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [LocalId] VARCHAR (111)  NOT NULL , [ShortName] VARCHAR (111)  NOT NULL , [LongName] VARCHAR (111)  NULL , [GroupType] VARCHAR (111)  NULL , [Set] VARCHAR (111)  NULL , [Block] VARCHAR (111)  NULL , [CurriculumLevel] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolLocalId] VARCHAR (111)  NULL , [SchoolCourseInfoRefId] VARCHAR (111)  NULL , [SchoolCourseLocalId] VARCHAR (111)  NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL , [TimeTableSubjectLocalId] VARCHAR (111)  NULL , [KeyLearningArea] VARCHAR (111)  NULL , [Semester] bigint  NULL , [MinClassSize] bit  NULL , [MaxClassSize] bit  NULL , CONSTRAINT [TeachingGroupKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.TimeTablePeriod ( [PeriodId] VARCHAR (111)  NOT NULL , [PeriodTitle] VARCHAR (111)  NOT NULL , [BellPeriod] VARCHAR (111)  NULL , [StartTime] datetime  NULL , [EndTime] datetime  NULL , [RegularSchoolPeriod] VARCHAR (111)  NULL , [InstructionalMinutes] bigint  NULL , [UseInAttendanceCalculations] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentSubjectChoice ( [PreferenceNumber] bigint  NULL , [SubjectLocalId] VARCHAR (111)  NOT NULL , [OtherSchoolLocalId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ToSchool ( [TravelMode] VARCHAR (111)  NULL , [TravelDetails] VARCHAR (111)  NULL , [TravelAccompaniment] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TimeTableCell ( [RefId] VARCHAR (111)  NOT NULL , [TimeTableRefId] VARCHAR (111)  NOT NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL , [TeachingGroupRefId] VARCHAR (111)  NOT NULL , [RoomInfoRefId] VARCHAR (111)  NULL , [StaffPersonalRefId] VARCHAR (111)  NULL , [TimeTableLocalId] VARCHAR (111)  NULL , [SubjectLocalId] VARCHAR (111)  NULL , [TeachingGroupLocalId] VARCHAR (111)  NULL , [RoomNumber] VARCHAR (111)  NULL , [StaffLocalId] VARCHAR (111)  NULL , [DayId] VARCHAR (111)  NOT NULL , [PeriodId] VARCHAR (111)  NOT NULL , [CellType] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolLocalId] VARCHAR (111)  NULL , CONSTRAINT [TimeTableCellKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.TimeTable ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolYear] smallint  NOT NULL , [LocalId] VARCHAR (111)  NULL , [Title] VARCHAR (111)  NOT NULL , [DaysPerCycle] bigint  NOT NULL , [PeriodsPerDay] bigint  NOT NULL , [TeachingPeriodsPerDay] bigint  NULL , [SchoolLocalId] VARCHAR (111)  NULL , [SchoolName] VARCHAR (111)  NULL , [TimeTableCreationDate] datetime  NULL , [StartDate] datetime  NULL , [EndDate] datetime  NULL , CONSTRAINT [TimeTableKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.TimeTableContainer ( [RefId] VARCHAR (111)  NOT NULL , CONSTRAINT [TimeTableContainerKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.StudentGroup ( [GroupCategory] VARCHAR (111)  NOT NULL , [GroupLocalId] VARCHAR (111)  NOT NULL , [GroupDescription] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentSectionEnrollment ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SectionInfoRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NULL , [EntryDate] datetime  NULL , [ExitDate] datetime  NULL , CONSTRAINT [StudentSectionEnrollmentKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.TimeTableDay ( [DayId] VARCHAR (111)  NOT NULL , [DayTitle] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TimeTableSchedule ( [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolYear] smallint  NOT NULL , [LocalId] VARCHAR (111)  NULL , [Title] VARCHAR (111)  NOT NULL , [DaysPerCycle] bigint  NOT NULL , [PeriodsPerDay] bigint  NOT NULL , [TeachingPeriodsPerDay] bigint  NULL , [SchoolLocalId] VARCHAR (111)  NULL , [SchoolName] VARCHAR (111)  NULL , [TimeTableCreationDate] datetime  NULL , [StartDate] datetime  NULL , [EndDate] datetime  NULL ) ;
CREATE TABLE cdm_demo_gold.TeachingGroupScheduleList ( [EditorGUID] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [LocalId] VARCHAR (111)  NOT NULL , [ShortName] VARCHAR (111)  NOT NULL , [LongName] VARCHAR (111)  NULL , [GroupType] VARCHAR (111)  NULL , [Set] VARCHAR (111)  NULL , [Block] VARCHAR (111)  NULL , [CurriculumLevel] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolLocalId] VARCHAR (111)  NULL , [SchoolCourseInfoRefId] VARCHAR (111)  NULL , [SchoolCourseLocalId] VARCHAR (111)  NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL , [TimeTableSubjectLocalId] VARCHAR (111)  NULL , [Semester] bigint  NULL , [MinClassSize] bit  NULL , [MaxClassSize] bit  NULL ) ;
CREATE TABLE cdm_demo_gold.TimeTableSubject ( [RefId] VARCHAR (111)  NOT NULL , [SubjectLocalId] VARCHAR (111)  NOT NULL , [CourseLocalId] VARCHAR (111)  NULL , [SchoolCourseInfoRefId] VARCHAR (111)  NULL , [Faculty] VARCHAR (111)  NULL , [SubjectShortName] VARCHAR (111)  NULL , [SubjectLongName] VARCHAR (111)  NOT NULL , [SubjectType] VARCHAR (111)  NULL , [ProposedMaxClassSize] decimal (38, 38)  NULL , [ProposedMinClassSize] decimal (38, 38)  NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [SchoolLocalId] VARCHAR (111)  NULL , [Semester] bigint  NULL , [SchoolYear] smallint  NULL , CONSTRAINT [TimeTableSubjectKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Start ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.End ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.WellbeingAppeal ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [WellbeingResponseRefId] VARCHAR (111)  NOT NULL , [LocalAppealId] VARCHAR (111)  NULL , [AppealStatusCode] VARCHAR (111)  NULL , [Date] datetime  NULL , [AppealNotes] VARCHAR (111)  NULL , [AppealOutcome] VARCHAR (111)  NULL , CONSTRAINT [WellbeingAppealKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Medication ( [MedicationName] VARCHAR (111)  NULL , [Dosage] VARCHAR (111)  NULL , [Frequency] VARCHAR (111)  NULL , [AdministrationInformation] VARCHAR (111)  NULL , [Method] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.WellbeingEventCategory ( [EventCategory] VARCHAR (255)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.VendorInfo ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [Name] VARCHAR (111)  NOT NULL , [CustomerId] VARCHAR (111)  NULL , [ABN] VARCHAR (111)  NULL , [RegisteredForGST] VARCHAR (111)  NULL , [PaymentTerms] VARCHAR (111)  NULL , [BPay] VARCHAR (111)  NULL , [BSB] VARCHAR (111)  NULL , [AccountNumber] VARCHAR (111)  NULL , [AccountName] VARCHAR (111)  NULL , CONSTRAINT [VendorInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.WellbeingAlert ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL , [WellbeingAlertStartDate] datetime  NULL , [WellbeingAlertEndDate] datetime  NULL , [WellbeingAlertCategory] VARCHAR (111)  NULL , [WellbeingAlertDescription] VARCHAR (111)  NULL , [EnrolmentRestricted] VARCHAR (111)  NULL , [AlertAudience] VARCHAR (111)  NULL , [AlertSeverity] VARCHAR (111)  NULL , [AlertKeyContact] VARCHAR (111)  NULL , CONSTRAINT [WellbeingAlertKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.WellbeingCharacteristic ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NULL , [WellbeingCharacteristicClassification] VARCHAR (111)  NULL , [WellbeingCharacteristicStartDate] datetime  NULL , [WellbeingCharacteristicEndDate] datetime  NULL , [WellbeingCharacteristicReviewDate] datetime  NULL , [WellbeingCharacteristicNotes] VARCHAR (111)  NULL , [WellbeingCharacteristicCategory] VARCHAR (255)  NULL , [WellbeingCharacteristicSubCategory] VARCHAR (255)  NULL , [LocalCharacteristicCode] VARCHAR (111)  NULL , [CharacteristicSeverity] VARCHAR (111)  NULL , [DailyManagement] VARCHAR (111)  NULL , [EmergencyManagement] VARCHAR (111)  NULL , [PreferredHospital] VARCHAR (111)  NULL , [EmergencyResponsePlan] VARCHAR (111)  NULL , [Trigger] VARCHAR (111)  NULL , [ConfidentialFlag] VARCHAR (111)  NULL , [Alert] VARCHAR (111)  NULL , CONSTRAINT [WellbeingCharacteristicKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.SymptomList ( [Symptom] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.WellbeingEvent ( [RefId] VARCHAR (111)  NOT NULL , [StudentPersonalRefId] VARCHAR (111)  NULL , [GroupIndicator] bit  NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [EventId] VARCHAR (111)  NULL , [WellbeingEventNotes] VARCHAR (111)  NULL , [WellbeingEventCategoryClass] VARCHAR (111)  NOT NULL , [ReportingStaffRefId] VARCHAR (111)  NULL , [WellbeingEventCreationTimeStamp] VARCHAR (255)  NULL , [WellbeingEventDate] datetime  NOT NULL , [WellbeingEventTime] datetime  NULL , [WellbeingEventDescription] VARCHAR (111)  NULL , [WellbeingEventTimePeriod] VARCHAR (111)  NOT NULL , [ConfidentialFlag] VARCHAR (111)  NULL , [Status] VARCHAR (111)  NULL , CONSTRAINT [WellbeingEventKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.WellbeingEventSubCategoryList ( [WellbeingEventSubCategory] VARCHAR (255)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.WellbeingEventLocationDetails ( [EventLocation] VARCHAR (111)  NOT NULL , [Class] VARCHAR (111)  NULL , [FurtherLocationNotes] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.PersonInvolvement ( [ShortName] VARCHAR (111)  NULL , [HowInvolved] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.PersonRefId ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.FollowUpAction ( [WellbeingResponseRefId] VARCHAR (111)  NULL , [FollowUpDetails] VARCHAR (111)  NULL , [FollowUpActionCategory] VARCHAR (111)  NULL , [Date] datetime  NULL ) ;
CREATE TABLE cdm_demo_gold.WellbeingResponse ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL , [WellbeingResponseStartDate] datetime  NOT NULL , [WellbeingResponseEndDate] datetime  NULL , [WellbeingResponseCategory] VARCHAR (111)  NULL , [WellbeingResponseNotes] VARCHAR (111)  NULL , CONSTRAINT [WellbeingResponseKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.PlanRequired ( [Status] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Suspension ( [SuspensionCategory] VARCHAR (111)  NOT NULL , [SuspensionNotes] VARCHAR (111)  NULL , [Duration] decimal (38, 38)  NULL , [AdvisementDate] datetime  NULL , [ResolutionMeetingTime] VARCHAR (255)  NULL , [ResolutionNotes] VARCHAR (111)  NULL , [EarlyReturnDate] datetime  NULL , [Status] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Withdrawal ( [WithdrawalDate] datetime  NOT NULL , [WithdrawalStartTime] datetime  NULL , [WithdrawalEndTime] datetime  NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL , [ScheduledActivityRefId] VARCHAR (111)  NULL , [TimeTableCellRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Detention ( [DetentionCategory] VARCHAR (111)  NOT NULL , [DetentionDate] datetime  NULL , [DetentionLocation] VARCHAR (111)  NULL , [DetentionNotes] VARCHAR (111)  NULL , [Status] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Plan ( [PersonalisedPlanRefId] VARCHAR (111)  NULL , [PlanNotes] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Award ( [AwardDate] datetime  NULL , [AwardType] VARCHAR (111)  NULL , [AwardDescription] VARCHAR (111)  NULL , [AwardNotes] VARCHAR (111)  NULL , [Status] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.WellbeingPersonLink ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [WellbeingEventRefId] VARCHAR (111)  NOT NULL , [WellbeingResponseRefId] VARCHAR (111)  NULL , [GroupId] VARCHAR (111)  NOT NULL , [ShortName] VARCHAR (111)  NULL , [HowInvolved] VARCHAR (111)  NULL , [OtherPersonId] VARCHAR (111)  NULL , [OtherPersonContactDetails] VARCHAR (111)  NULL , [PersonRole] VARCHAR (111)  NULL , CONSTRAINT [WellbeingPersonLinkKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.OtherResponse ( [OtherResponseDate] datetime  NULL , [OtherResponseType] VARCHAR (111)  NULL , [OtherResponseDescription] VARCHAR (111)  NULL , [OtherResponseNotes] VARCHAR (111)  NULL , [Status] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentAttendance ( [CountsTowardAttendance] VARCHAR (111)  NOT NULL , [AttendanceValue] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AdministratorAttendance ( [CountsTowardAttendance] VARCHAR (111)  NOT NULL , [AttendanceValue] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Location ( [LocationName] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NULL , [ReferenceType] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TeacherAttendance ( [CountsTowardAttendance] VARCHAR (111)  NOT NULL , [AttendanceValue] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Characteristics ( [AggregateCharacteristicInfoRefId] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.YearLevel ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AggregateStatisticInfo ( [RefId] VARCHAR (111)  NOT NULL , [StatisticName] VARCHAR (111)  NOT NULL , [ApprovalDate] datetime  NULL , [ExpirationDate] datetime  NULL , [Source] VARCHAR (111)  NULL , [EffectiveDate] datetime  NULL , [DiscontinueDate] datetime  NULL , [Measure] VARCHAR (111)  NULL , CONSTRAINT [AggregateStatisticInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.CensusCollection ( [RefId] VARCHAR (111)  NOT NULL , [CensusYear] smallint  NOT NULL , [RoundCode] VARCHAR (111)  NOT NULL , CONSTRAINT [CensusCollectionKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.AggregateCharacteristicInfo ( [RefId] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [Definition] VARCHAR (111)  NOT NULL , [ElementName] VARCHAR (111)  NULL , CONSTRAINT [AggregateCharacteristicInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ParentAddress ( [EffectiveFromDate] datetime  NULL , [EffectiveToDate] datetime  NULL , [City] VARCHAR (111)  NOT NULL , [StateProvince] VARCHAR (255)  NULL , [Country] VARCHAR (111)  NULL , [PostalCode] VARCHAR (111)  NOT NULL , [RadioContact] VARCHAR (111)  NULL , [Community] VARCHAR (111)  NULL , [LocalId] VARCHAR (111)  NULL , [AddressGlobalUID] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL , [Role] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Parent2 ( [AddressSameAsStudent] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ExclusionRule ( [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CalculationRule ( [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LocationRefId ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CalendarDate ( [CalendarDateRefId] VARCHAR (111)  NOT NULL , [Date] datetime  NOT NULL , [CalendarSummaryRefId] VARCHAR (111)  NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [CalendarDateNumber] bigint  NULL , CONSTRAINT [CalendarDateKey1] PRIMARY KEY ( [CalendarDateRefId] ) ) ;
CREATE TABLE cdm_demo_gold.CalendarDateType ( [Code] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.CalendarSummary ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NOT NULL , [LocalId] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [DaysInSession] bigint  NOT NULL , [StartDate] datetime  NULL , [EndDate] datetime  NULL , [FirstInstructionDate] datetime  NULL , [LastInstructionDate] datetime  NULL , [GraduationDate] VARCHAR (255)  NULL , [InstructionalMinutes] bigint  NULL , [MinutesPerDay] bigint  NULL , CONSTRAINT [CalendarSummaryKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.CensusReporting ( [EntityLevel] VARCHAR (111)  NULL , [CommonwealthId] VARCHAR (111)  NOT NULL , [EntityName] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.AggregateStatisticFact ( [RefId] VARCHAR (111)  NOT NULL , [AggregateStatisticInfoRefId] VARCHAR (111)  NOT NULL , [Excluded] VARCHAR (111)  NULL , [Value] decimal (38, 38)  NOT NULL , CONSTRAINT [AggregateStatisticFactKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.AGContextualQuestion ( [AGContextCode] VARCHAR (111)  NOT NULL , [AGAnswer] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StatisticalArea ( [SpatialUnitType] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Email ( [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.MapReference ( [XCoordinate] VARCHAR (111)  NOT NULL , [YCoordinate] VARCHAR (111)  NOT NULL , [MapNumber] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.StudentAddress ( [EffectiveFromDate] datetime  NULL , [EffectiveToDate] datetime  NULL , [City] VARCHAR (111)  NOT NULL , [StateProvince] VARCHAR (255)  NULL , [Country] VARCHAR (111)  NULL , [PostalCode] VARCHAR (111)  NOT NULL , [RadioContact] VARCHAR (111)  NULL , [Community] VARCHAR (111)  NULL , [LocalId] VARCHAR (111)  NULL , [AddressGlobalUID] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL , [Role] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Parent1 ( [AddressSameAsStudent] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PhoneNumber ( [Number] VARCHAR (111)  NOT NULL , [Extension] VARCHAR (111)  NULL , [ListedStatus] VARCHAR (111)  NULL , [Preference] bigint  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.AddressCollectionStudent ( [LocalId] VARCHAR (111)  NOT NULL , [EducationLevel] VARCHAR (111)  NOT NULL , [BoardingStatus] VARCHAR (111)  NULL , [ReportingParent2] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ParentName ( [Title] VARCHAR (111)  NULL , [FamilyName] VARCHAR (111)  NULL , [GivenName] VARCHAR (111)  NULL , [MiddleName] VARCHAR (111)  NULL , [FamilyNameFirst] VARCHAR (111)  NULL , [PreferredFamilyName] VARCHAR (111)  NULL , [PreferredFamilyNameFirst] VARCHAR (111)  NULL , [PreferredGivenName] VARCHAR (111)  NULL , [Suffix] VARCHAR (111)  NULL , [FullName] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Street ( [Line1] VARCHAR (111)  NULL , [Line2] VARCHAR (111)  NULL , [Line3] VARCHAR (111)  NULL , [Complex] VARCHAR (111)  NULL , [StreetNumber] VARCHAR (111)  NULL , [StreetPrefix] VARCHAR (111)  NULL , [StreetName] VARCHAR (111)  NULL , [StreetType] VARCHAR (111)  NULL , [StreetSuffix] VARCHAR (111)  NULL , [ApartmentType] VARCHAR (111)  NULL , [ApartmentNumberPrefix] VARCHAR (111)  NULL , [ApartmentNumber] VARCHAR (111)  NULL , [ApartmentNumberSuffix] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.GridLocation ( [Latitude] decimal (38, 38)  NOT NULL , [Longitude] decimal (38, 38)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TotalAmount ( [Currency] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Document ( [Location] VARCHAR (111)  NOT NULL , [Sensitivity] VARCHAR (111)  NULL , [URL] VARCHAR (111)  NULL , [DocumentType] VARCHAR (111)  NULL , [DocumentReviewDate] datetime  NULL , [DocumentDescription] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.TeacherCover ( [StaffPersonalRefId] VARCHAR (111)  NOT NULL , [StaffLocalId] VARCHAR (111)  NULL , [StartTime] datetime  NULL , [FinishTime] datetime  NULL , [Credit] VARCHAR (111)  NULL , [Supervision] VARCHAR (111)  NULL , [Weighting] decimal (38, 38)  NULL ) ;
CREATE TABLE cdm_demo_gold.StudentList ( [StudentPersonalRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Override ( [DateOfOverride] datetime  NULL ) ;
CREATE TABLE cdm_demo_gold.SchoolCourseInfo ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [SchoolLocalId] VARCHAR (111)  NULL , [SchoolYear] smallint  NULL , [TermInfoRefId] VARCHAR (111)  NULL , [CourseCode] VARCHAR (111)  NOT NULL , [StateCourseCode] VARCHAR (111)  NULL , [DistrictCourseCode] VARCHAR (111)  NULL , [CourseTitle] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [InstructionalLevel] VARCHAR (111)  NULL , [CourseCredits] VARCHAR (111)  NULL , [CoreAcademicCourse] VARCHAR (111)  NULL , [GraduationRequirement] VARCHAR (111)  NULL , [Department] VARCHAR (111)  NULL , [CourseContent] VARCHAR (111)  NULL , CONSTRAINT [SchoolCourseInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.SettingLocation ( [SettingLocationName] VARCHAR (111)  NULL , [SettingLocationType] VARCHAR (111)  NULL , [SettingLocationRefId] VARCHAR (111)  NULL , [SettingLocationObjectTypeName] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.PurchaseOrder ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [FormNumber] VARCHAR (111)  NOT NULL , [VendorInfoRefId] VARCHAR (111)  NOT NULL , [ChargedLocationInfoRefId] VARCHAR (111)  NULL , [EmployeePersonalRefId] VARCHAR (111)  NULL , [CreationDate] datetime  NULL , [TaxRate] decimal (38, 38)  NULL , [UpdateDate] datetime  NULL , [FullyDelivered] VARCHAR (111)  NULL , [OriginalPurchaseOrderRefId] VARCHAR (111)  NULL , CONSTRAINT [PurchaseOrderKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ResourceBooking ( [RefId] VARCHAR (111)  NOT NULL , [ResourceLocalId] VARCHAR (111)  NOT NULL , [StartDateTime] VARCHAR (255)  NOT NULL , [FinishDateTime] VARCHAR (255)  NOT NULL , [FromPeriod] VARCHAR (111)  NULL , [ToPeriod] VARCHAR (111)  NULL , [Booker] VARCHAR (111)  NOT NULL , [Reason] VARCHAR (111)  NULL , [ScheduledActivityRefId] VARCHAR (111)  NULL , [KeepOld] bit  NULL , CONSTRAINT [ResourceBookingKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ResourceRefId ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.DataDomainObligation ( [DataDomain] VARCHAR (111)  NOT NULL , [DomainComments] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ShareWith ( [ShareWithParty] VARCHAR (111)  NOT NULL , [ShareWithRefId] VARCHAR (111)  NULL , [ShareWithObjectTypeName] VARCHAR (111)  NULL , [ShareWithLocalId] VARCHAR (111)  NULL , [ShareWithName] VARCHAR (111)  NULL , [ShareWithRelationship] VARCHAR (111)  NULL , [ShareWithPurpose] VARCHAR (111)  NOT NULL , [ShareWithRole] VARCHAR (111)  NOT NULL , [ShareWithComments] VARCHAR (111)  NULL , [PermissionToOnShare] VARCHAR (111)  NOT NULL , [ShareWithURL] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.DoNotShareWith ( [DoNotShareWithParty] VARCHAR (111)  NOT NULL , [DoNotShareWithRefId] VARCHAR (111)  NULL , [DoNotShareWithObjectTypeName] VARCHAR (111)  NULL , [DoNotShareWithLocalId] VARCHAR (111)  NULL , [DoNotShareWithName] VARCHAR (111)  NULL , [DoNotShareWithRelationship] VARCHAR (111)  NULL , [DoNotShareWithPurpose] VARCHAR (111)  NOT NULL , [DoNotShareWithRole] VARCHAR (111)  NOT NULL , [DoNotShareWithComments] VARCHAR (111)  NULL , [DoNotShareWithURL] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.PermissionToParticipate ( [PermissionCategory] VARCHAR (111)  NOT NULL , [Permission] VARCHAR (111)  NOT NULL , [PermissionValue] VARCHAR (111)  NULL , [PermissionStartDate] datetime  NULL , [PermissionEndDate] datetime  NULL , [PermissionGranteeRefId] VARCHAR (111)  NULL , [PermissionGranteeObjectTypeName] VARCHAR (111)  NULL , [PermissionGranteeName] VARCHAR (111)  NULL , [PermissionGranteeRelationship] VARCHAR (111)  NULL , [PermissionComments] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ApplicableLaw ( [ApplicableCountry] VARCHAR (111)  NOT NULL , [ApplicableLawName] VARCHAR (111)  NOT NULL , [ApplicableLawURL] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.NeverShareWith ( [NeverShareWithParty] VARCHAR (111)  NOT NULL , [NeverShareWithRefId] VARCHAR (111)  NULL , [NeverShareWithObjectTypeName] VARCHAR (111)  NULL , [NeverShareWithLocalId] VARCHAR (111)  NULL , [NeverShareWithName] VARCHAR (111)  NULL , [NeverShareWithRelationship] VARCHAR (111)  NULL , [NeverShareWithPurpose] VARCHAR (111)  NOT NULL , [NeverShareWithRole] VARCHAR (111)  NOT NULL , [NeverShareWithComments] VARCHAR (111)  NULL , [NeverShareWithURL] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.PersonalisedPlan ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [StudentPersonalRefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [PersonalisedPlanCategory] VARCHAR (111)  NOT NULL , [PersonalisedPlanStartDate] datetime  NOT NULL , [PersonalisedPlanEndDate] datetime  NULL , [PersonalisedPlanReviewDate] datetime  NULL , [PersonalisedPlanNotes] VARCHAR (111)  NULL , [AssociatedAttachment] VARCHAR (111)  NULL , CONSTRAINT [PersonalisedPlanKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.RoomInfo ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [RoomNumber] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [Building] VARCHAR (111)  NULL , [HomeroomNumber] VARCHAR (111)  NULL , [Size] decimal (38, 38)  NULL , [Capacity] bigint  NULL , [RoomType] VARCHAR (111)  NULL , [AvailableForTimetable] VARCHAR (111)  NULL , CONSTRAINT [RoomInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.ScheduledActivity ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [TimeTableCellRefId] VARCHAR (111)  NULL , [DayId] VARCHAR (111)  NULL , [PeriodId] VARCHAR (111)  NULL , [TimeTableRefId] VARCHAR (111)  NULL , [ActivityDate] datetime  NOT NULL , [ActivityEndDate] datetime  NULL , [StartTime] datetime  NOT NULL , [FinishTime] datetime  NOT NULL , [CellType] VARCHAR (111)  NULL , [TimeTableSubjectRefId] VARCHAR (111)  NULL , [Location] VARCHAR (111)  NULL , [ActivityType] VARCHAR (111)  NULL , [ActivityName] VARCHAR (111)  NULL , [ActivityComment] VARCHAR (111)  NULL , [OverridePatch] bit  NULL , CONSTRAINT [ScheduledActivityKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.RoomList ( [RoomInfoRefId] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TeachingGroupList ( [TeachingGroupRefId] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TimeTableChangeReason ( [TimeTableChangeType] VARCHAR (111)  NOT NULL , [TimeTableChangeNotes] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SchoolFocusList ( [SchoolFocus] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.SchoolContact ( [PublishInDirectory] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.OtherId ( [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.YearLevelEnrollment ( [Year] VARCHAR (111)  NOT NULL , [Enrollment] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TotalEnrollments ( [Girls] VARCHAR (111)  NULL , [Boys] VARCHAR (111)  NULL , [TotalStudents] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.SchoolGroupList ( [SchoolGroup] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.ContactName ( [Title] VARCHAR (111)  NULL , [FamilyName] VARCHAR (111)  NULL , [GivenName] VARCHAR (111)  NULL , [MiddleName] VARCHAR (111)  NULL , [FamilyNameFirst] VARCHAR (111)  NULL , [PreferredFamilyName] VARCHAR (111)  NULL , [PreferredFamilyNameFirst] VARCHAR (111)  NULL , [PreferredGivenName] VARCHAR (111)  NULL , [Suffix] VARCHAR (111)  NULL , [FullName] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.OtherLEA ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.SchoolPrograms ( [RefId] VARCHAR (111)  NOT NULL , [SchoolInfoRefId] VARCHAR (111)  NOT NULL , [SchoolYear] smallint  NULL , CONSTRAINT [SchoolProgramsKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.PrincipalInfo ( [ContactTitle] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Program ( [Category] VARCHAR (111)  NULL , [Type] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.SchoolInfo ( [RefId] VARCHAR (111)  NOT NULL , [LocalId] VARCHAR (111)  NULL , [StateProvinceId] VARCHAR (111)  NULL , [CommonwealthId] VARCHAR (111)  NULL , [ParentCommonwealthId] VARCHAR (111)  NULL , [ACARAId] VARCHAR (111)  NULL , [SchoolName] VARCHAR (111)  NOT NULL , [LEAInfoRefId] VARCHAR (111)  NULL , [SchoolDistrict] VARCHAR (111)  NULL , [SchoolDistrictLocalId] VARCHAR (111)  NULL , [SchoolType] VARCHAR (111)  NULL , [SchoolURL] VARCHAR (111)  NULL , [SessionType] VARCHAR (111)  NULL , [ARIA] decimal (38, 38)  NULL , [OperationalStatus] VARCHAR (111)  NULL , [FederalElectorate] VARCHAR (111)  NULL , [SchoolSector] VARCHAR (111)  NOT NULL , [IndependentSchool] VARCHAR (111)  NULL , [NonGovSystemicStatus] VARCHAR (111)  NULL , [System] VARCHAR (111)  NULL , [ReligiousAffiliation] VARCHAR (111)  NULL , [SchoolGeographicLocation] VARCHAR (111)  NULL , [LocalGovernmentArea] VARCHAR (111)  NULL , [JurisdictionLowerHouse] VARCHAR (111)  NULL , [SLA] VARCHAR (111)  NULL , [SchoolCoEdStatus] VARCHAR (111)  NULL , [BoardingSchoolStatus] VARCHAR (111)  NULL , [Entity_Open] datetime  NULL , [Entity_Close] datetime  NULL , [SchoolTimeZone] VARCHAR (111)  NULL , CONSTRAINT [SchoolInfoKey1] PRIMARY KEY ( [RefId] ) ) ;
CREATE TABLE cdm_demo_gold.Campus ( [ParentSchoolId] VARCHAR (111)  NULL , [ParentSchoolRefId] VARCHAR (111)  NULL , [SchoolCampusId] VARCHAR (111)  NOT NULL , [CampusType] VARCHAR (111)  NULL , [AdminStatus] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.Created ( [DateTime] VARCHAR (255)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.SIF_Metadata ( [ETag] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.ActivityTime ( [CreationDate] datetime  NOT NULL , [StartDate] datetime  NULL , [FinishDate] datetime  NULL , [DueDate] datetime  NULL ) ;
CREATE TABLE cdm_demo_gold.Duration ( [Units] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LearningResources ( [LearningResourceRefId] VARCHAR (111)  NULL ) ;
CREATE TABLE cdm_demo_gold.Evaluation ( [Description] VARCHAR (111)  NULL , [EvaluationType] VARCHAR (111)  NOT NULL , [RefId] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.LocalCode ( [LocalisedCode] VARCHAR (111)  NOT NULL , [Description] VARCHAR (111)  NULL , [Element] VARCHAR (111)  NULL , [ListIndex] bit  NULL ) ;
CREATE TABLE cdm_demo_gold.SpanGap ( [StartDateTime] VARCHAR (255)  NULL , [EndDateTime] VARCHAR (255)  NULL ) ;
CREATE TABLE cdm_demo_gold.SourceObject ( [SIF_RefObject] VARCHAR (111)  NOT NULL ) ;
CREATE TABLE cdm_demo_gold.TimeElement ( [StartDateTime] VARCHAR (255)  NULL , [EndDateTime] VARCHAR (255)  NULL , [IsCurrent] bit  NOT NULL ) ;

	
      -- [/noformat]
